FROM apache/airflow:2.9.3-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install required Airflow providers
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.9.0 \
    apache-airflow-providers-docker==3.12.0 \
    apache-airflow-providers-common-sql==1.26.0
