name: 'nyc_taxi_gold'
version: '1.0.0'
config-version: 2

profile: 'gold_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  nyc_taxi_gold:
    analytics:
      +materialized: table
      +schema: gold
