gold_profile:
  target: prod
  outputs:
    prod:
      type: trino
      method: none
      host: trino
      port: 8080
      user: trino
      catalog: lakehouse
      schema: gold
      threads: 4
      connect_retries: 3
      connect_timeout: 10
